<?php
/**
 * Language labels for plugin "tx_newloginbox_pi3"
 *
 * TYPO3 CVS ID: $Id: locallang.php 3630 2006-08-29 20:27:45Z ingmars $
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'listFieldHeader_username' => 'Username:',
		'listFieldHeader_name' => 'Name:',
		'listFieldHeader_email' => 'Email:',
		'listFieldHeader_country' => 'Country:',
		'listFieldHeader_city' => 'City',
		'listFieldHeader_zip' => 'Zipcode',
		'listFieldHeader_telephone' => 'Telephone',
		'listFieldHeader_address' => 'Address',
		'listFieldHeader_title' => 'Title',
		'listFieldHeader_homepage' => 'Homepage',
		'listFieldHeader_company' => 'Company',
		'listFieldHeader_fax' => 'Fax',
		'listFieldHeader_contribute' => 'What I wish to contribute:',
		'listFieldHeader_personallife' => 'My personal life:',
		'listFieldHeader_typo3experiences' => 'Experience:',
		'listFieldHeader_image' => 'Image:',
		'listFieldHeader_www' => 'Web:',
		'pi_list_browseresults_prev' => '< Previous',
		'pi_list_browseresults_next' => 'Next >',
		'pi_list_browseresults_displays' => 'Displaying users ###SPAN_BEGIN###%s to %s</span> out of ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Search',
		'singleview_created' => 'Created:',
		'singleview_lastLogin' => 'Last login:',
		'singleview_detailsAbout' => 'Details about',
		'singleview_limitedDetailsAbout' => 'Limited details about',
		'singleview_back' => 'Back',
	),
	'dk' => Array (
		'listFieldHeader_username' => 'Brugernavn:',
		'listFieldHeader_name' => 'Navn:',
		'listFieldHeader_email' => 'Email:',
		'listFieldHeader_country' => 'Land:',
		'listFieldHeader_city' => 'By:',
		'listFieldHeader_zip' => 'Postnr:',
		'listFieldHeader_telephone' => 'Telefon:',
		'listFieldHeader_address' => 'Adresse:',
		'listFieldHeader_title' => 'Titel:',
		'listFieldHeader_homepage' => 'Hjemmeside:',
		'listFieldHeader_company' => 'Firma:',
		'listFieldHeader_fax' => 'Fax:',
		'listFieldHeader_contribute' => 'Hvad jeg vil bidrage med:',
		'listFieldHeader_personallife' => 'Mit personlige liv:',
		'listFieldHeader_typo3experiences' => 'Erfaring:',
		'pi_list_browseresults_page' => 'Side',
		'pi_list_browseresults_prev' => '< Forrige',
		'pi_list_browseresults_next' => 'Næste >',
		'pi_list_browseresults_displays' => 'Viser brugere ###SPAN_BEGIN###%s til %s</span> ud af ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Søg',
		'singleview_created' => 'Oprettet:',
		'singleview_lastLogin' => 'Sidste login:',
		'singleview_detailsAbout' => 'Detaljer om',
		'singleview_limitedDetailsAbout' => 'Begrænsede detaljer om',
		'singleview_back' => 'Tilbage',
	),
	'de' => Array (
		'listFieldHeader_username' => 'Benutzername:',
		'listFieldHeader_name' => 'Name:',
		'listFieldHeader_email' => 'Email:',
		'listFieldHeader_country' => 'Land:',
		'listFieldHeader_city' => 'Stadt',
		'listFieldHeader_zip' => 'PLZ',
		'listFieldHeader_telephone' => 'Telefon',
		'listFieldHeader_address' => 'Adresse',
		'listFieldHeader_title' => 'Titel',
		'listFieldHeader_homepage' => 'Homepage',
		'listFieldHeader_company' => 'Firma',
		'listFieldHeader_fax' => 'Fax',
		'listFieldHeader_contribute' => 'Was ich beitragen möchte:',
		'listFieldHeader_personallife' => 'Mein Leben:',
		'listFieldHeader_typo3experiences' => 'Erfahrung:',
		'listFieldHeader_image' => 'Bild:',
		'listFieldHeader_www' => 'Web:',
		'pi_list_browseresults_page' => 'Seite',
		'pi_list_browseresults_prev' => '< Vorherige',
		'pi_list_browseresults_next' => 'Nächste >',
		'pi_list_browseresults_displays' => 'Zeige Benutzer ###SPAN_BEGIN###%s bis %s</span> von insg. ###SPAN_BEGIN###%s an</span>',
		'pi_list_searchBox_search' => 'Suche',
		'singleview_created' => 'Erstellt:',
		'singleview_lastLogin' => 'Letzter Login:',
		'singleview_detailsAbout' => 'Alle Informationen zu',
		'singleview_limitedDetailsAbout' => 'Eingeschränkte Informationen zu',
		'singleview_back' => 'Zurück',
	),
	'no' => Array (
		'listFieldHeader_username' => 'Brukernavn:',
		'listFieldHeader_name' => 'Navn:',
		'listFieldHeader_email' => 'E-post:',
		'listFieldHeader_country' => 'Land:',
		'listFieldHeader_city' => 'By:',
		'listFieldHeader_zip' => 'Postnr:',
		'listFieldHeader_telephone' => 'Telefon:',
		'listFieldHeader_address' => 'Adresse:',
		'listFieldHeader_title' => 'Tittel:',
		'listFieldHeader_homepage' => 'Hjemmeside:',
		'listFieldHeader_company' => 'Firma:',
		'listFieldHeader_fax' => 'Faks:',
		'listFieldHeader_contribute' => 'Hva jeg ønsker å bidra med:',
		'listFieldHeader_personallife' => 'Mitt personlige liv:',
		'listFieldHeader_typo3experiences' => 'Erfaring:',
		'pi_list_browseresults_prev' => '< Forrige',
		'pi_list_browseresults_next' => 'Neste >',
		'pi_list_browseresults_displays' => 'Viser brukere ###SPAN_BEGIN###%s til %s</span> av ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Søk',
	),
	'it' => Array (
		'listFieldHeader_username' => 'Username:',
		'listFieldHeader_name' => 'Nome:',
		'listFieldHeader_email' => 'Email:',
		'listFieldHeader_country' => 'Stato:',
		'listFieldHeader_city' => 'Città',
		'listFieldHeader_zip' => 'CAP',
		'listFieldHeader_telephone' => 'Telefono',
		'listFieldHeader_address' => 'Indirizzo',
		'listFieldHeader_title' => 'Titolo',
		'listFieldHeader_homepage' => 'Homepage',
		'listFieldHeader_company' => 'Azienda',
		'listFieldHeader_fax' => 'Fax',
		'listFieldHeader_contribute' => 'Desidero contribuire nel seguente modo:',
		'listFieldHeader_personallife' => 'La mia vita privata:',
		'listFieldHeader_typo3experiences' => 'Esperienza:',
		'listFieldHeader_image' => 'Immagine:',
		'listFieldHeader_www' => 'Web:',
		'pi_list_browseresults_prev' => '< indietro',
		'pi_list_browseresults_next' => 'avanti >',
		'pi_list_browseresults_displays' => 'Utenti da ###SPAN_BEGIN###%s a %s</span> su ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Cerca',
		'singleview_created' => 'Creato:',
		'singleview_lastLogin' => 'Ultimo login:',
		'singleview_detailsAbout' => 'Dettagli su',
		'singleview_limitedDetailsAbout' => 'Dettagli limitati',
		'singleview_back' => 'Indietro',
	),
	'fr' => Array (
		'listFieldHeader_username' => 'Identifiant',
		'listFieldHeader_name' => 'Nom',
		'listFieldHeader_email' => 'Email',
		'listFieldHeader_country' => 'Pays',
		'listFieldHeader_city' => 'Ville',
		'listFieldHeader_zip' => 'Code Postal',
		'listFieldHeader_telephone' => 'Téléphone',
		'listFieldHeader_address' => 'Adresse',
		'listFieldHeader_title' => 'Titre',
		'listFieldHeader_homepage' => 'Page d\'accueil',
		'listFieldHeader_company' => 'Société',
		'listFieldHeader_fax' => 'Fax',
		'listFieldHeader_contribute' => 'Mes voeux de contribution',
		'listFieldHeader_personallife' => 'Moi ma vie',
		'listFieldHeader_typo3experiences' => 'Expérience',
		'listFieldHeader_image' => 'Photo',
		'listFieldHeader_www' => 'Web',
		'pi_list_browseresults_prev' => 'Précédent',
		'pi_list_browseresults_next' => 'Suivant',
		'pi_list_browseresults_displays' => 'Affichage des utilisateurs ###SPAN_BEGIN###%s à %s</span> sur ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Rechercher',
		'singleview_created' => 'Création',
		'singleview_lastLogin' => 'Dernière connexion',
		'singleview_detailsAbout' => 'Détails à propos de',
		'singleview_limitedDetailsAbout' => 'Détails limités à propos de',
		'singleview_back' => 'Retour',
	),
	'es' => Array (
		'listFieldHeader_username' => 'Nombre de usuario:',
		'listFieldHeader_name' => 'Nombre:',
		'listFieldHeader_email' => 'E-mail:',
		'listFieldHeader_country' => 'País:',
		'listFieldHeader_city' => 'Ciudad:',
		'listFieldHeader_zip' => 'Código Postal:',
		'listFieldHeader_telephone' => 'Teléfono:',
		'listFieldHeader_address' => 'Dirección:',
		'listFieldHeader_title' => 'Cargo:',
		'listFieldHeader_homepage' => 'Dirección WEB:',
		'listFieldHeader_company' => 'Empresa:',
		'listFieldHeader_fax' => 'Fax:',
		'listFieldHeader_contribute' => 'Con qué pretendo contribuir:',
		'listFieldHeader_personallife' => 'Mi vida personal:',
		'listFieldHeader_typo3experiences' => 'Experiencia:',
		'pi_list_browseresults_page' => 'Página',
		'pi_list_browseresults_prev' => '< Anterior',
		'pi_list_browseresults_next' => 'Siguiente >',
		'pi_list_browseresults_displays' => 'Mostrando usuarios ###SPAN_BEGIN###del %s al %s</span> de un total de ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Buscar',
	),
	'nl' => Array (
		'listFieldHeader_username' => 'Gebruikersnaam:',
		'listFieldHeader_name' => 'Naam:',
		'listFieldHeader_email' => 'Email:',
		'listFieldHeader_country' => 'Land:',
		'listFieldHeader_city' => 'Stad',
		'listFieldHeader_zip' => 'Postcode',
		'listFieldHeader_telephone' => 'Telefoon',
		'listFieldHeader_address' => 'Adres',
		'listFieldHeader_title' => 'Titel',
		'listFieldHeader_homepage' => 'Homepage:',
		'listFieldHeader_company' => 'Bedrijf',
		'listFieldHeader_fax' => 'Fax:',
		'listFieldHeader_contribute' => 'Wat ik wil bijdragen:',
		'listFieldHeader_personallife' => 'Mijn persoonlijke leven:',
		'listFieldHeader_typo3experiences' => 'Ervaring:',
		'listFieldHeader_image' => 'Afbeelding:',
		'listFieldHeader_www' => 'Web:',
		'pi_list_browseresults_prev' => '< Vorige',
		'pi_list_browseresults_next' => 'Volgende >',
		'pi_list_browseresults_displays' => 'Weergegeven gebruikers ###SPAN_BEGIN###%s tot %s</span> van de ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Zoeken',
		'singleview_created' => 'Aangemaak:',
		'singleview_lastLogin' => 'Laatst ingelogd:',
		'singleview_detailsAbout' => 'Details van',
		'singleview_limitedDetailsAbout' => 'Beperk details van',
		'singleview_back' => 'Terug',
	),
	'cz' => Array (
		'listFieldHeader_username' => 'Pøihlašovací jméno:',
		'listFieldHeader_name' => 'Jméno a pøíjmení:',
		'listFieldHeader_email' => 'Email:',
		'listFieldHeader_country' => 'Zemì:',
		'listFieldHeader_city' => 'Mìsto',
		'listFieldHeader_zip' => 'PSÈ',
		'listFieldHeader_telephone' => 'Telefon',
		'listFieldHeader_address' => 'Adresa',
		'listFieldHeader_title' => 'Název',
		'listFieldHeader_homepage' => 'Domovská stránka',
		'listFieldHeader_company' => 'Spoleènost',
		'listFieldHeader_fax' => 'Fax',
		'listFieldHeader_contribute' => 'Na èem se chci zde podílet:',
		'listFieldHeader_personallife' => 'Mùj osobní život:',
		'listFieldHeader_typo3experiences' => 'Zkušenosti:',
		'listFieldHeader_image' => 'Obrázek:',
		'listFieldHeader_www' => 'Web:',
		'pi_list_browseresults_prev' => '< Pøedchozí',
		'pi_list_browseresults_next' => 'Další >',
		'pi_list_browseresults_displays' => 'Zobrazuji uživatele ###SPAN_BEGIN###%s až %s</span>, celkem z ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Hledání',
		'singleview_created' => 'Vytvoøeno:',
		'singleview_lastLogin' => 'Poslední pøihlášení:',
		'singleview_detailsAbout' => 'Detaily',
		'singleview_limitedDetailsAbout' => 'Základní detaily',
		'singleview_back' => 'Zpìt',
	),
	'pl' => Array (
		'listFieldHeader_username' => 'U¿ytkownik:',
		'listFieldHeader_name' => 'Nazwa:',
		'listFieldHeader_email' => 'Email:',
		'listFieldHeader_country' => 'Kraj:',
		'listFieldHeader_city' => 'Miasto',
		'listFieldHeader_zip' => 'Kod pocztowy',
		'listFieldHeader_telephone' => 'Telefon',
		'listFieldHeader_address' => 'Adres',
		'listFieldHeader_title' => 'Tytu³',
		'listFieldHeader_homepage' => 'Strona domowa',
		'listFieldHeader_company' => 'Firma',
		'listFieldHeader_fax' => 'Faks',
		'listFieldHeader_contribute' => 'Co chcê wnie¶æ/czym chcê siê podzieliæ:',
		'listFieldHeader_personallife' => '¯ycie prywatne:',
		'listFieldHeader_typo3experiences' => 'Do¶wiadczenie:',
		'listFieldHeader_image' => 'Zdjêcie:',
		'listFieldHeader_www' => 'Strona www:',
		'pi_list_browseresults_prev' => '< Poprzednia',
		'pi_list_browseresults_next' => 'Nastêpna >',
		'pi_list_browseresults_displays' => 'Wy¶wietlanie u¿ytkowników ###SPAN_BEGIN###%s do %s</span> z ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Szukaj',
		'singleview_created' => 'Utworzono:',
		'singleview_lastLogin' => 'Ostatnie logowanie:',
		'singleview_detailsAbout' => 'Szczegó³y',
		'singleview_limitedDetailsAbout' => 'Wybrane szczegó³y',
		'singleview_back' => 'Powrót',
	),
	'si' => Array (
	),
	'fi' => Array (
		'listFieldHeader_username' => 'Käyttäjätunnus:',
		'listFieldHeader_name' => 'Nimi:',
		'listFieldHeader_email' => 'Sähköpostiosoite:',
		'listFieldHeader_country' => 'Maa:',
		'listFieldHeader_city' => 'Kaupunki:',
		'listFieldHeader_zip' => 'Postinumero:',
		'listFieldHeader_telephone' => 'Puhelin:',
		'listFieldHeader_address' => 'Osoite:',
		'listFieldHeader_title' => 'Arvo:',
		'listFieldHeader_homepage' => 'Kotisivu:',
		'listFieldHeader_company' => 'Yritys;',
		'listFieldHeader_fax' => 'Fax:',
		'listFieldHeader_contribute' => 'Miten haluat osallsitua:',
		'listFieldHeader_personallife' => 'Henkilökohtaista:',
		'listFieldHeader_typo3experiences' => 'Kokemus:',
		'listFieldHeader_image' => 'Kuva:',
		'listFieldHeader_www' => 'Kotisivut:',
		'pi_list_browseresults_prev' => '< Edellinen',
		'pi_list_browseresults_next' => 'Seuraava >',
		'pi_list_browseresults_displays' => 'Näytän käyttäjät alkaen ###SPAN_BEGIN###%s aina %s</span> saakka kaikkiaan ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Haku',
		'singleview_created' => 'Luotu:',
		'singleview_lastLogin' => 'Viime sisäänkirjoitus:',
		'singleview_detailsAbout' => 'Tarkat tiedot',
		'singleview_limitedDetailsAbout' => 'Rajoitetut tiedot',
		'singleview_back' => 'Takaisin',
	),
	'tr' => Array (
		'listFieldHeader_username' => 'Kullanýcý adý:',
		'listFieldHeader_name' => 'Ad/Soyad:',
		'listFieldHeader_email' => 'E-posta:',
		'listFieldHeader_country' => 'Ülke:',
		'listFieldHeader_city' => 'Þehir',
		'listFieldHeader_zip' => 'Posta kodu',
		'listFieldHeader_telephone' => 'Telefon',
		'listFieldHeader_address' => 'Adres',
		'listFieldHeader_title' => 'Ünvan',
		'listFieldHeader_homepage' => 'Website',
		'listFieldHeader_company' => 'Þirket',
		'listFieldHeader_fax' => 'Faks',
		'listFieldHeader_contribute' => 'Ne ile katýlmak istediðim:',
		'listFieldHeader_personallife' => 'Özel hayatým:',
		'listFieldHeader_typo3experiences' => 'Deneyim:',
		'listFieldHeader_image' => 'Resim:',
		'listFieldHeader_www' => 'Web:',
		'pi_list_browseresults_prev' => '< Önceki',
		'pi_list_browseresults_next' => 'Sonraki >',
		'pi_list_browseresults_displays' => '###SPAN_BEGIN###%s-%s</span> arasý kayýtlar, toplam ###SPAN_BEGIN###%s</span> kayýt',
		'pi_list_searchBox_search' => 'Ara',
		'singleview_created' => 'Oluþturma tarihi:',
		'singleview_lastLogin' => 'Son oturum açma:',
		'singleview_detailsAbout' => 'Hakkýnda ayrýntýlar',
		'singleview_limitedDetailsAbout' => 'Hakkýnda kýsýtlý ayrýntýlar',
		'singleview_back' => 'Geri',
	),
	'se' => Array (
		'listFieldHeader_username' => 'Användarnamn:',
		'listFieldHeader_name' => 'Namn:',
		'listFieldHeader_email' => 'Epost:',
		'listFieldHeader_country' => 'Land:',
		'listFieldHeader_city' => 'Postadress',
		'listFieldHeader_zip' => 'Postnummer',
		'listFieldHeader_telephone' => 'Telefon',
		'listFieldHeader_address' => 'Adress',
		'listFieldHeader_title' => 'Titel',
		'listFieldHeader_homepage' => 'Hemsida',
		'listFieldHeader_company' => 'Företag',
		'listFieldHeader_fax' => 'Fax',
		'listFieldHeader_contribute' => 'Hur jag vill delta:',
		'listFieldHeader_personallife' => 'Mitt personliga liv:',
		'listFieldHeader_typo3experiences' => 'Erfarenhet:',
		'pi_list_browseresults_prev' => '< Tidigare',
		'pi_list_browseresults_next' => 'Nästa >',
		'pi_list_browseresults_displays' => 'Visar användare ###SPAN_BEGIN###%s till %s</span> av ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Sök',
	),
	'pt' => Array (
		'listFieldHeader_username' => 'Utilizador:',
		'listFieldHeader_name' => 'Nome:',
		'listFieldHeader_email' => 'E-mail:',
		'listFieldHeader_country' => 'País:',
		'listFieldHeader_city' => 'Cidade',
		'listFieldHeader_zip' => 'Código Postal',
		'listFieldHeader_telephone' => 'Telefone',
		'listFieldHeader_address' => 'Endereço',
		'listFieldHeader_title' => 'Título',
		'listFieldHeader_homepage' => 'Homepage',
		'listFieldHeader_company' => 'Compania',
		'listFieldHeader_fax' => 'Fax',
		'listFieldHeader_contribute' => 'Em que eu quero contribuir:',
		'listFieldHeader_personallife' => 'Minha vida:',
		'listFieldHeader_typo3experiences' => 'Experiência:',
		'pi_list_browseresults_prev' => '< Anterior',
		'pi_list_browseresults_next' => 'Próxima >',
		'pi_list_browseresults_displays' => 'Mostrando utilizadores de ###SPAN_BEGIN###%s a %s</span> de um total de ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Pesquisar',
	),
	'ru' => Array (
		'listFieldHeader_username' => 'Èìÿ ïîëüçîâàòåëÿ:',
		'listFieldHeader_name' => 'Âàøå èìÿ è ôàìèëèÿ:',
		'listFieldHeader_email' => 'Email (àäðåñ ýëåêòðîííîé ïî÷òû):',
		'listFieldHeader_country' => 'Ñòðàíà:',
		'listFieldHeader_city' => 'Ãîðîä',
		'listFieldHeader_zip' => 'Ïî÷òîâûé èíäåêñ',
		'listFieldHeader_telephone' => 'Òåëåôîí',
		'listFieldHeader_address' => 'Ïî÷òîâûé àäðåñ',
		'listFieldHeader_title' => 'Òèòóë, çâàíèå',
		'listFieldHeader_homepage' => 'Àäðåñ âåá-ñàéòà',
		'listFieldHeader_company' => 'Íàçâàíèå êîìïàíèè',
		'listFieldHeader_fax' => 'Òåëåôàêñ',
		'listFieldHeader_contribute' => 'Ïîæåëàíèÿ:',
		'listFieldHeader_personallife' => 'Àíêåòà:',
		'listFieldHeader_typo3experiences' => 'Îïûò:',
		'listFieldHeader_image' => 'Ôîòîãðàôèÿ:',
		'listFieldHeader_www' => 'Àäðåñ âåá-ñàéòà:',
		'pi_list_browseresults_prev' => '< ïðåäûäóùèå',
		'pi_list_browseresults_next' => 'ñëåäóþùèå >',
		'pi_list_browseresults_displays' => 'Îòîáðàæåíèå ïîëüçîâàòåëåé ###SPAN_BEGIN###%s ïî %s</span> èç ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Ïîèñê',
		'singleview_created' => 'Ñîçäàíà:',
		'singleview_lastLogin' => 'Ïîñëåäíèé âõîä:',
		'singleview_detailsAbout' => 'Èíôîðìàöèÿ î',
		'singleview_limitedDetailsAbout' => 'Îãðàíè÷åííàÿ èíôîðìàöèÿ î',
		'singleview_back' => 'Íàçàä',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
		'listFieldHeader_username' => 'Korisnièko ime:',
		'listFieldHeader_name' => 'Ime',
		'listFieldHeader_email' => 'E-mail:',
		'listFieldHeader_country' => 'Država:',
		'listFieldHeader_city' => 'Grad',
		'listFieldHeader_zip' => 'Poštanski broj',
		'listFieldHeader_telephone' => 'Telefon',
		'listFieldHeader_address' => 'Adresa',
		'listFieldHeader_title' => 'Naslov',
		'listFieldHeader_homepage' => 'Home stranica',
		'listFieldHeader_company' => 'Tvrtka',
		'listFieldHeader_fax' => 'Faks',
		'listFieldHeader_contribute' => 'Što želim raditi:',
		'listFieldHeader_personallife' => 'Privatni život:',
		'listFieldHeader_typo3experiences' => 'Iskustvo:',
		'listFieldHeader_image' => 'Slika:',
		'listFieldHeader_www' => 'Web:',
		'pi_list_browseresults_prev' => '< Prethodna',
		'pi_list_browseresults_next' => 'Sljedeæa >',
		'pi_list_browseresults_displays' => 'prikazujem korisnike od ###SPAN_BEGIN###%s do %s</span> od ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Traži',
		'singleview_created' => 'Napravljano_',
		'singleview_lastLogin' => 'Zadnja prijava:',
		'singleview_detailsAbout' => 'Detaljnije o',
		'singleview_limitedDetailsAbout' => 'Ogranièeni detalji o',
		'singleview_back' => 'Natrag',
	),
	'hu' => Array (
	),
	'gl' => Array (
		'listFieldHeader_username' => 'Atuisup aqqa:',
		'listFieldHeader_name' => 'Ateq:',
		'listFieldHeader_email' => 'Email:',
		'listFieldHeader_country' => 'Nuna:',
		'listFieldHeader_city' => 'Illoqarfik:',
		'listFieldHeader_zip' => 'Postnormu:',
		'listFieldHeader_telephone' => 'Oqarasuaat:',
		'listFieldHeader_address' => 'Adresse:',
		'listFieldHeader_title' => 'Atorfik:',
		'listFieldHeader_homepage' => 'Nittartagaq:',
		'listFieldHeader_company' => 'Suliffik:',
		'listFieldHeader_fax' => 'Fax:',
		'listFieldHeader_contribute' => 'Imatut tapeeqataarusuppunga:',
		'listFieldHeader_personallife' => 'Inuttut inuunera:',
		'listFieldHeader_typo3experiences' => 'Misilittakkakka:',
		'pi_list_browseresults_prev' => '< Siulia',
		'pi_list_browseresults_next' => 'Tullia >',
		'pi_list_browseresults_displays' => 'Atuisut ###SPAN_BEGIN###%s</span> akornanni ###SPAN_BEGIN###%s-miit %s-mut</span> takutinneqarput',
		'pi_list_searchBox_search' => 'Ujaruk',
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'listFieldHeader_username' => 'Usuário:',
		'listFieldHeader_name' => 'Nome:',
		'listFieldHeader_email' => 'E-Mail:',
		'listFieldHeader_country' => 'País:',
		'listFieldHeader_city' => 'Cidade',
		'listFieldHeader_zip' => 'CEP',
		'listFieldHeader_telephone' => 'Telefone',
		'listFieldHeader_address' => 'Endereço',
		'listFieldHeader_title' => 'Título',
		'listFieldHeader_homepage' => 'Homepage',
		'listFieldHeader_company' => 'Empresa',
		'listFieldHeader_fax' => 'Fax',
		'listFieldHeader_contribute' => 'Em que eu quero contribuir:',
		'listFieldHeader_personallife' => 'Minha vida:',
		'listFieldHeader_typo3experiences' => 'Experiência:',
		'listFieldHeader_image' => 'Imagem:',
		'listFieldHeader_www' => 'Website:',
		'pi_list_browseresults_prev' => '< Anterior',
		'pi_list_browseresults_next' => 'Próxima >',
		'pi_list_browseresults_displays' => 'Exibindo usuários de ###SPAN_BEGIN###%s a %s</span> de um total de ###SPAN_BEGIN###%s</span>',
		'pi_list_searchBox_search' => 'Pesquisar',
		'singleview_created' => 'Criação',
		'singleview_lastLogin' => 'Último login:',
		'singleview_detailsAbout' => 'Detalhes sobre',
		'singleview_limitedDetailsAbout' => 'Resumo sobre',
		'singleview_back' => 'Voltar',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>