<?php
/**
 * Language labels for extension "newloginbox"
 * 
 * TYPO3 CVS ID: $Id: locallang_db.php 3653 2006-09-02 10:02:16Z ingmars $
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'tt_content.list_type1' => 'Better login-box',
		'tt_content.list_type3' => 'User Listing',
		'tt_content.pi_flexform.header' => 'Header:',
		'tt_content.pi_flexform.message' => 'Message:',
		'tt_content.pi_flexform.sheet_general' => 'General',
		'tt_content.pi_flexform.sheet_welcome' => 'Welcome',
		'tt_content.pi_flexform.sheet_success' => 'Login Success',
		'tt_content.pi_flexform.sheet_error' => 'Login Error',
		'tt_content.pi_flexform.sheet_status' => 'Status',
		'tt_content.pi_flexform.sheet_logout' => 'Logout',
		'tt_content.pi_flexform.show_forgot_password' => 'Show "Forgot password?" link:',
		'tt_content.pi_flexform.show_permalogin' => 'Show "Stay logged in" checkbox (if switched on for the installation):',
		'tt_content.pi_flexform.field_manualOrder' => 'Using fieldlists below:',
		'tt_content.pi_flexform.field_orderList' => 'User Fields/list:',
		'tt_content.pi_flexform.field_orderDetails' => 'User Fields/details:',
	),
	'dk' => Array (
		'tt_content.list_type1' => 'Bedre login-boks',
		'tt_content.list_type3' => 'Brugerliste',
		'tt_content.pi_flexform.header' => 'Overskrift:',
		'tt_content.pi_flexform.message' => 'Tekst:',
		'tt_content.pi_flexform.sheet_general' => 'Generelle valg',
		'tt_content.pi_flexform.sheet_welcome' => 'Velkomst',
		'tt_content.pi_flexform.sheet_success' => 'Login Succes',
		'tt_content.pi_flexform.sheet_error' => 'Login Fejl',
		'tt_content.pi_flexform.sheet_status' => 'Status',
		'tt_content.pi_flexform.sheet_logout' => 'Logout',
		'tt_content.pi_flexform.show_forgot_password' => 'Vis "Glemt password?" link:',
	),
	'de' => Array (
		'tt_content.list_type1' => 'Besseres Anmeldeformular',
		'tt_content.list_type3' => 'Benutzerliste',
		'tt_content.pi_flexform.header' => 'Ьberschrift:',
		'tt_content.pi_flexform.message' => 'Nachricht:',
		'tt_content.pi_flexform.sheet_general' => 'Allgemein',
		'tt_content.pi_flexform.sheet_welcome' => 'Willkommen',
		'tt_content.pi_flexform.sheet_success' => 'Erfolgreich angemeldet',
		'tt_content.pi_flexform.sheet_error' => 'Anmeldefehler',
		'tt_content.pi_flexform.sheet_status' => 'Status',
		'tt_content.pi_flexform.sheet_logout' => 'Abmelden',
		'tt_content.pi_flexform.show_forgot_password' => '"Passwort vergessen?" Link anzeigen:',
		'tt_content.pi_flexform.show_permalogin' => '"Eingeloggt bleiben" checkbox anzeigen (wenn auf dem System verfьgbar)',
		'tt_content.pi_flexform.field_manualOrder' => 'Folgende Felder benutzen:',
		'tt_content.pi_flexform.field_orderList' => 'Listenansicht:',
		'tt_content.pi_flexform.field_orderDetails' => 'Detailansicht:',
	),
	'no' => Array (
		'tt_content.list_type1' => 'Bedre innloggingsboks',
		'tt_content.list_type3' => 'Brukerliste',
		'tt_content.pi_flexform.header' => 'Overskrift:',
		'tt_content.pi_flexform.message' => 'Tekst:',
		'tt_content.pi_flexform.sheet_general' => 'Generelle valg',
		'tt_content.pi_flexform.sheet_welcome' => 'Velkomstmelding',
		'tt_content.pi_flexform.sheet_success' => 'Vellykket innlogging',
		'tt_content.pi_flexform.sheet_error' => 'Feil ved innlogging',
		'tt_content.pi_flexform.sheet_status' => 'Status',
		'tt_content.pi_flexform.sheet_logout' => 'Logg ut',
		'tt_content.pi_flexform.show_forgot_password' => 'Vis "Glemt passordet?"-lenke',
		'tt_content.pi_flexform.field_manualOrder' => 'Bruk feltlisten under:',
		'tt_content.pi_flexform.field_orderList' => 'Brukerfelter/liste:',
		'tt_content.pi_flexform.field_orderDetails' => 'Brukerfelter/detaljer:',
	),
	'it' => Array (
		'tt_content.list_type1' => 'Nuovo login-box',
		'tt_content.list_type3' => 'Elenco utenti',
		'tt_content.pi_flexform.header' => 'Intestazione:',
		'tt_content.pi_flexform.message' => 'Messaggio:',
		'tt_content.pi_flexform.sheet_general' => 'Generale:',
		'tt_content.pi_flexform.sheet_welcome' => 'Benvenuto',
		'tt_content.pi_flexform.sheet_success' => 'Login avvenuto',
		'tt_content.pi_flexform.sheet_error' => 'Errore di Login',
		'tt_content.pi_flexform.sheet_status' => 'Stato',
		'tt_content.pi_flexform.sheet_logout' => 'Logout',
		'tt_content.pi_flexform.show_forgot_password' => 'Mostra link "Dimenticato la password?":',
		'tt_content.pi_flexform.field_manualOrder' => 'Usa i campi sottostanti:',
		'tt_content.pi_flexform.field_orderList' => 'Campi Utente/lista:',
		'tt_content.pi_flexform.field_orderDetails' => 'Campi Utente/dettagli:',
	),
	'fr' => Array (
		'tt_content.list_type1' => 'Formulaire d\'identification avancй',
		'tt_content.list_type3' => 'Liste des utilisateurs',
		'tt_content.pi_flexform.header' => 'Titre',
		'tt_content.pi_flexform.message' => 'Message',
		'tt_content.pi_flexform.sheet_general' => 'Gйnйral',
		'tt_content.pi_flexform.sheet_welcome' => 'Bienvenue',
		'tt_content.pi_flexform.sheet_success' => 'Succиs',
		'tt_content.pi_flexform.sheet_error' => 'Erreur',
		'tt_content.pi_flexform.sheet_status' => 'Йtat',
		'tt_content.pi_flexform.sheet_logout' => 'Dйconnexion',
		'tt_content.pi_flexform.show_forgot_password' => 'Affichй le lien "Mot de passe oubliй?"',
		'tt_content.pi_flexform.field_manualOrder' => 'Utiliser les champs suivant:',
		'tt_content.pi_flexform.field_orderList' => 'Champs (liste)',
		'tt_content.pi_flexform.field_orderDetails' => 'Champs (dйtails)',
	),
	'es' => Array (
		'tt_content.list_type1' => 'Formulario de login mejorado',
		'tt_content.list_type3' => 'Lista de usuarios',
	),
	'nl' => Array (
		'tt_content.list_type1' => 'Verbeterde login-box',
		'tt_content.list_type3' => 'Gebruikers Lijst',
		'tt_content.pi_flexform.header' => 'Kop:',
		'tt_content.pi_flexform.message' => 'Bericht:',
		'tt_content.pi_flexform.sheet_general' => 'Algemeen',
		'tt_content.pi_flexform.sheet_welcome' => 'Welkom',
		'tt_content.pi_flexform.sheet_success' => 'Inloggen gelukt',
		'tt_content.pi_flexform.sheet_error' => 'Fout bij het inloggen',
		'tt_content.pi_flexform.sheet_status' => 'Status',
		'tt_content.pi_flexform.sheet_logout' => 'Uitloggen',
		'tt_content.pi_flexform.show_forgot_password' => 'Toon "Password vergeten?" link:',
		'tt_content.pi_flexform.field_manualOrder' => 'Gebruik veldlijst hieronder:',
		'tt_content.pi_flexform.field_orderList' => 'Gebruikers velden/lijst:',
		'tt_content.pi_flexform.field_orderDetails' => 'Gebruikers velden/details:',
	),
	'cz' => Array (
		'tt_content.list_type1' => 'Lepљн pшihlaљovacн box',
		'tt_content.list_type3' => 'Vэpis uћivatelщ',
		'tt_content.pi_flexform.header' => 'Nadpis',
		'tt_content.pi_flexform.message' => 'Zprбva:',
		'tt_content.pi_flexform.sheet_general' => 'Obecnй',
		'tt_content.pi_flexform.sheet_welcome' => 'Vнtejte',
		'tt_content.pi_flexform.sheet_success' => 'Ъspмљnй pшihlбљenн',
		'tt_content.pi_flexform.sheet_error' => 'Chyba pшihlбљenн',
		'tt_content.pi_flexform.sheet_status' => 'Stav',
		'tt_content.pi_flexform.sheet_logout' => 'Odhlбљenн',
		'tt_content.pi_flexform.show_forgot_password' => 'Zobrazovat odkaz "Zapomмli jste svй heslo"?',
		'tt_content.pi_flexform.field_manualOrder' => 'Pouћнvбm vэиet polн dole:',
		'tt_content.pi_flexform.field_orderList' => 'Uћivatelskб pole/vэиet:',
		'tt_content.pi_flexform.field_orderDetails' => 'Uћivatelskб pole/detaily:',
	),
	'pl' => Array (
		'tt_content.list_type1' => 'Lepszy formularz logowania',
		'tt_content.list_type3' => 'Lista uїytkownikуw',
		'tt_content.pi_flexform.header' => 'Nagіуwek:',
		'tt_content.pi_flexform.message' => 'Wiadomo¶ж:',
		'tt_content.pi_flexform.sheet_general' => 'Ogуlne',
		'tt_content.pi_flexform.sheet_welcome' => 'Powitanie',
		'tt_content.pi_flexform.sheet_success' => 'Udane logowanie',
		'tt_content.pi_flexform.sheet_error' => 'Bікdne logowanie',
		'tt_content.pi_flexform.sheet_status' => 'Status',
		'tt_content.pi_flexform.sheet_logout' => 'Wylogowanie',
		'tt_content.pi_flexform.show_forgot_password' => 'Pokazuj odno¶nik "zapomniaіem hasіo":',
		'tt_content.pi_flexform.field_manualOrder' => 'Uїycie listy pуl poniїej:',
		'tt_content.pi_flexform.field_orderList' => 'Pola uїytkownika/lista:',
		'tt_content.pi_flexform.field_orderDetails' => 'Pola uїytkownika/szczegуіy:',
	),
	'si' => Array (
	),
	'fi' => Array (
		'tt_content.list_type1' => 'Parempi sisддnkirjoitus-boxi',
		'tt_content.list_type3' => 'Kдyttдjдn listaus',
		'tt_content.pi_flexform.header' => 'Otsikko:',
		'tt_content.pi_flexform.message' => 'Viesti',
		'tt_content.pi_flexform.sheet_general' => 'Yleistд',
		'tt_content.pi_flexform.sheet_welcome' => 'Tervetulotoivotus',
		'tt_content.pi_flexform.sheet_success' => 'Onnistunut sisддnkirjoitus',
		'tt_content.pi_flexform.sheet_error' => 'Epдonnistunut sisддnkirjoitus',
		'tt_content.pi_flexform.sheet_status' => 'Tila',
		'tt_content.pi_flexform.sheet_logout' => 'Ulos kirjoittautuminen',
		'tt_content.pi_flexform.show_forgot_password' => 'Nдytд "Unohditko salasanasi ?" linkki:',
		'tt_content.pi_flexform.field_manualOrder' => 'Kдytetддn allaolevaa tietolistaa:',
		'tt_content.pi_flexform.field_orderList' => 'Kдyttдjдn tiedot/lista:',
		'tt_content.pi_flexform.field_orderDetails' => 'Kдyttдjдn tiedot/tarkat tiedot:',
	),
	'tr' => Array (
		'tt_content.list_type1' => 'Daha iyi oturum aзma kutusu',
		'tt_content.list_type3' => 'Kullanэcэ listesi',
		'tt_content.pi_flexform.header' => 'Baюlэk:',
		'tt_content.pi_flexform.message' => 'Mesaj:',
		'tt_content.pi_flexform.sheet_general' => 'Genel',
		'tt_content.pi_flexform.sheet_welcome' => 'Hoюgeldin',
		'tt_content.pi_flexform.sheet_success' => 'Oturum baюarэyla aзэldэ',
		'tt_content.pi_flexform.sheet_error' => 'Oturum aзmada hata',
		'tt_content.pi_flexform.sheet_status' => 'Statь',
		'tt_content.pi_flexform.sheet_logout' => 'Oturumu kapat',
		'tt_content.pi_flexform.show_forgot_password' => '\'Parola kayэp?\' linkini gцster:',
		'tt_content.pi_flexform.field_manualOrder' => 'Altdaki alan listelerini kullan:',
		'tt_content.pi_flexform.field_orderList' => 'Liste gцrьntьsь',
		'tt_content.pi_flexform.field_orderDetails' => 'Detaylэ gцrьntь',
	),
	'se' => Array (
		'tt_content.list_type1' => 'En bдttre login-box',
		'tt_content.list_type3' => 'Anvдndarlista',
	),
	'pt' => Array (
		'tt_content.list_type1' => 'Janela de acesso aprimorada',
		'tt_content.list_type3' => 'Lista de utilizadores',
	),
	'ru' => Array (
		'tt_content.list_type1' => 'Улучшенный вход в систему',
		'tt_content.list_type3' => 'Список пользователей',
		'tt_content.pi_flexform.header' => 'Заголовок:',
		'tt_content.pi_flexform.message' => 'Сообщение:',
		'tt_content.pi_flexform.sheet_general' => 'Общие',
		'tt_content.pi_flexform.sheet_welcome' => 'Добро пожаловать!',
		'tt_content.pi_flexform.sheet_success' => 'Успешный вход',
		'tt_content.pi_flexform.sheet_error' => 'Ошибка входа',
		'tt_content.pi_flexform.sheet_status' => 'Статус',
		'tt_content.pi_flexform.sheet_logout' => 'Выход',
		'tt_content.pi_flexform.show_forgot_password' => 'Показывать ссылку "Забыли пароль?"',
		'tt_content.pi_flexform.field_manualOrder' => 'Используя список полей внизу:',
		'tt_content.pi_flexform.field_orderList' => 'Поля в режиме списка пользователей:',
		'tt_content.pi_flexform.field_orderDetails' => 'Поля в режиме деталей пользователя:',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
		'tt_content.list_type1' => 'Bolji login-box',
		'tt_content.list_type3' => 'Popis korisnika',
		'tt_content.pi_flexform.header' => 'Zaglavlje:',
		'tt_content.pi_flexform.message' => 'Poruka:',
		'tt_content.pi_flexform.sheet_general' => 'Opжenito',
		'tt_content.pi_flexform.sheet_welcome' => 'Dobrodoљli',
		'tt_content.pi_flexform.sheet_success' => 'Prijava uspjeљna',
		'tt_content.pi_flexform.sheet_error' => 'Greљka pri prijavi',
		'tt_content.pi_flexform.sheet_status' => 'Status',
		'tt_content.pi_flexform.sheet_logout' => 'Odjava',
		'tt_content.pi_flexform.show_forgot_password' => 'Prikaћi "Zaboravljena lozinka?" link:',
		'tt_content.pi_flexform.field_manualOrder' => 'Koristeжi niћe navedena polja:',
		'tt_content.pi_flexform.field_orderList' => 'Korisniиka Polja/popis:',
		'tt_content.pi_flexform.field_orderDetails' => 'Korisniиka Polja/detalji:',
	),
	'hu' => Array (
	),
	'gl' => Array (
		'tt_content.list_type1' => 'Login-box pitsaanerusoq',
		'tt_content.list_type3' => 'Atuisut tulleriiarneri',
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'tt_content.list_type1' => 'Caixa de Identificaзгo Avanзada',
		'tt_content.list_type3' => 'Lista de usuбrios',
		'tt_content.pi_flexform.header' => 'Cabeзalho:',
		'tt_content.pi_flexform.message' => 'Mensagem:',
		'tt_content.pi_flexform.sheet_general' => 'Geral',
		'tt_content.pi_flexform.sheet_welcome' => 'Bem-vindo',
		'tt_content.pi_flexform.sheet_success' => 'Identificaзгo com Sucesso',
		'tt_content.pi_flexform.sheet_error' => 'Erro de Identificaзгo',
		'tt_content.pi_flexform.sheet_status' => 'Situaзгo',
		'tt_content.pi_flexform.sheet_logout' => 'Encerrar',
		'tt_content.pi_flexform.show_forgot_password' => 'Exibir o link "Esqueci minha senha?":',
		'tt_content.pi_flexform.field_manualOrder' => 'Utilizando os campos abaixo:',
		'tt_content.pi_flexform.field_orderList' => 'Campos de Usuбrio/Lista:',
		'tt_content.pi_flexform.field_orderDetails' => 'Campos de Usuбrio/Detalhes:',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
	'eo' => Array (
	),
	'my' => Array (
	),
	'hi' => Array (
	),
);
?>