<?php

/* This is hooked just after initFEuser (see /index.php and tslib/class.tslib_fe.php)
 * in ext_localconf.php. It stores an explicit selection (L=... in a link generated by
 * a language menu) in session, and restores it to $_GET[L] if present.
 */
function user_langsession($params, &$obj) {
  $L = t3lib_div::GPvar ('L');
//echo "LLL = $L";die();
  if ($L !== NULL) {
    /* Language explicitly selected via "L=[0-9]" GET request, store user whish in session */
    $lang = array('lang_id' => $L);
    $obj->fe_user->setKey('ses', 'lang', $lang);
  }
  else
  {
    /* Retrieve language from session (if available) */
    $lang = $obj->fe_user->getKey('ses', 'lang');
    $L = $lang['lang_id'];
    if ($L != NULL)
      $_GET['L'] = $L;
  }
}

?>
