<?php

$url_parlante = array(
"fle~0" => "blanche",
"fle~1" => "jaune",
"fle~2" => "rose",
"fle~3" => "rouge",
"fle~4" => "verte",
"fle~5" => "violette",
"fle~6" => "mauve",
"fle~7" => "bleue",
"feu~0" => "laniere",
"feu~1" => "allongee",
"feu~2" => "entiere",
"feu~3" => "decoupee",
"feu~4" => "pennee",
"feu~5" => "trifoliee",
"mil~0" => "Aquatique",
"mil~1" => "humide",
"mil~2" => "sec",
"mil~3" => "ni-sec-ni-humide",
"alt~0" => "moins-de-600-m",
"alt~1" => "de-600-a-1000-m",
"alt~2" => "plus-de-1000-m",
"por~0" => "dresse",
"por~1" => "rampant",
"por~2" => "intermediaire",
"tai~2.5" => "0-5-cm",
"tai~7.5" => "5-10-cm",
"tai~15" => "10-20-cm",
"tai~30" => "20-40-cm",
"tai~60" => "40-80-cm",
"tai~100" => "80-120-cm",
"tai~140" => "120-160-cm",
"tai~190" => "160-cm-ou-plus"
);

?>